name: Herokuapp Automation

on:
  push:
    branches: [ main ]
    paths:
      - 'herokuapp-automation/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Build with Gradle

        run: cd herokuapp-automation && gradle clean test -Dheadless.mode=true
      - name: Deploy Serenity Report
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-herokuapp
          folder: herokuapp-automation/target/site/serenity